name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:

  redploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to staging

    steps:
      - run : |
          echo : "Commited successfully"



